//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_ingenieria_software.BE {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLConsultas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLConsultas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proyecto_ingenieria_software.BE.SQLConsultas", typeof(SQLConsultas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT SCOPE_IDENTITY() AS ID.
        /// </summary>
        internal static string consultaIDInsertado {
            get {
                return ResourceManager.GetString("consultaIDInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT Rol.Descripcion FROM Usuario
        ///INNER JOIN Rol ON Usuario.IdRol = Rol.IdRol
        ///WHERE IdUsuario = &apos;{0}&apos;.
        /// </summary>
        internal static string consultaNombreRol {
            get {
                return ResourceManager.GetString("consultaNombreRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT IdRol, Descripcion FROM Rol.
        /// </summary>
        internal static string consultaRol {
            get {
                return ResourceManager.GetString("consultaRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT IdSexo, Descripcion FROM Sexo.
        /// </summary>
        internal static string consultaSexo {
            get {
                return ResourceManager.GetString("consultaSexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Empleado
        ///(Nombre, Apellido, Fecha_Nacimiento, Direccion, Dpi, Sexo)
        ///VALUES
        ///(&apos;{0}&apos;,&apos;{1}&apos;,&apos;{2}&apos;,&apos;{3}&apos;,&apos;{4}&apos;,{5}); SELECT SCOPE_IDENTITY() AS ID;.
        /// </summary>
        internal static string insertaEmpleado {
            get {
                return ResourceManager.GetString("insertaEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Usuario
        ///(IdUsuario, Contraseña, IdRol, IdEmpleado)
        ///VALUES
        ///(&apos;{0}&apos;,HASHBYTES(&apos;MD5&apos;,&apos;{1}&apos;),{2},{3}); .
        /// </summary>
        internal static string insertaUsuario {
            get {
                return ResourceManager.GetString("insertaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT &apos;1&apos; FROM Usuario
        ///WHERE IdUsuario=&apos;{0}&apos; AND Contraseña=HASHBYTES(&apos;MD5&apos;,&apos;{1}&apos;).
        /// </summary>
        internal static string validaUsuario {
            get {
                return ResourceManager.GetString("validaUsuario", resourceCulture);
            }
        }
    }
}
